datasources:
  default:
    url: jdbc:h2:mem:dogdatabase;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: 'sa'
    password: 'sa'
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    packages-to-scan:
      - 'com.solution.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true